const devs = [
  {
    id: 1,
    name: "Tahmid",
    age: 25,
    skill: "Mern Stack",
    location: "USA",
    income: 100000,
  },
  {
    id: 2,
    name: "Mahmud",
    age: 24,
    skill: "Mern Stack",
    location: "Dhaka",
    income: 10000,
  },
  {
    id: 3,
    name: "Mahdi",
    age: 34,
    skill: "IOS Devs",
    location: "Khulna",
    income: 20000,
  },
  {
    id: 4,
    name: "Mishrak",
    age: 30,
    skill: "BlockChain Devs",
    location: "Barisal",
    income: 30000,
  },
  {
    id: 5,
    name: "Tahmeed",
    age: 31,
    skill: "Django",
    location: "Comilla",
    income: 10001,
  },
  {
    id: 6,
    name: "Nusrat",
    age: 26,
    skill: "IOS Devs",
    location: "Rajshahi",
    income: 15000,
  },
  {
    id: 7,
    name: "Nurani",
    age: 51,
    skill: "Django",
    location: "USA",
    income: 17000,
  },
  {
    id: 8,
    name: "Kalam",
    age: 36,
    skill: "Mern Stack",
    location: "Shylet",
    income: 43000,
  },
  {
    id: 9,
    name: "Malek",
    age: 50,
    skill: "IOS Devs",
    location: "USA",
    income: 45000,
  },
  {
    id: 10,
    name: "Kamal",
    age: 44,
    skill: "Django",
    location: "Noakhali",
    income: 50000,
  },
  {
    id: 11,
    name: "Ishrak",
    age: 49,
    skill: "BlockChain Devs",
    location: "Dhaka",
    income: 51000,
  },
  {
    id: 12,
    name: "Nishan",
    age: 43,
    skill: "IOS Devs",
    location: "Khulna",
    income: 55000,
  },
  {
    id: 13,
    name: "Reza",
    age: 39,
    skill: "Django",
    location: "Rajshahi",
    income: 9000,
  },
  {
    id: 14,
    name: "Fahad",
    age: 37,
    skill: "BlockChain Devs",
    location: "Comilla",
    income: 12000,
  },
  {
    id: 15,
    name: "Progyya",
    age: 29,
    skill: "IOS Devs",
    location: "Diajpur",
    income: 24000,
  },
  {
    id: 16,
    name: "Shanita",
    age: 22,
    skill: "Mern Stack",
    location: "Dhaka",
    income: 38000,
  },
  {
    id: 17,
    name: "Nishi",
    age: 15,
    skill: "BlockChain Devs",
    location: "Khulna",
    income: 41000,
  },
  {
    id: 18,
    name: "Jamil",
    age: 55,
    skill: "Django",
    location: "Faridpur",
    income: 60000,
  },
  {
    id: 19,
    name: "Nanna",
    age: 45,
    skill: "IOS Devs",
    location: "Barisal",
    income: 59000,
  },
  {
    id: 20,
    name: "Raz",
    age: 35,
    skill: "Mern Stack",
    location: "USA",
    income: 90000,
  },
];
